
services:
  app_scrapad:
    container_name: app_scrapad
    image: app-scrapad:1.0.0
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://java_db:3306/scrapad?createDatabaseIfNotExist=true&serverTimezone=UTC
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    restart: always
    depends_on:
      java_db:
        condition: service_healthy

  java_db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: scrapad
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "java_db", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
